### ISSUE TITLE
the emperical risk used in ood_histogram.py

### ISSUE THREAD

**Issue by yyht** [aangelopoulos/ltt#2]
hi, this is a great work. However, 
    r_hats_risk2 = (calib_tables[:,1,:] * (1-calib_tables[:,0,:]) - alphas[1]*(1-calib_tables[:,0,:])).mean(axis=0).squeeze().flatten() + alphas[1] # empirical risk at each lambda combination using trick
I don't understand the trick used here. Can we replace thie trick and if we replace this trick, does it have impacts on final performance ?

**Comment by aangelopoulos** [comment]
The trick is the display under Eq. (4) on page 12 of the April 27, 2022 version of the LTT paper https://arxiv.org/abs/2110.01052.

You can replace the trick if you want, but you have to carefully back-calculate the risk.
