### ISSUE TITLE
Help needed in running the OOD test

### ISSUE THREAD

**Issue by alfassy** [aangelopoulos/ltt#3]
Hi Guys,
Thank you for the great paper, I am interested in your OOD experiment. I am trying to understand how to run OOD_histogram.py.
A few files are needed to be created for example: "softmax_scores_in_distribution.pt" . I noticed that the "odin" subfolder has the code to generate those but on line 69 of "odin/code/cal.py" a pretrained model is required: "../models/{}.pth".format(nnName)
Can you maybe provided pre-trained models and give some instructions as for how to run the OOD experiment?
Thank you in advance,
Amit

**Comment by aangelopoulos** [comment]
Hi Amit!

  I like your name, it is also the name of my closest friend :)

  If I recall correctly, you don't need to use `cal.py'.  Instead you can directly call this line, with your model of choice (such as a torchvision resnet): https://github.com/aangelopoulos/ltt/blob/c3fbb21f9914e14621b398edbd97e8ab3383bdb3/experiments/ood/odin/code/calData.py#L29

  This is what I did, I believe.  Sorry it's not more easily reproducible!

Best,
Anastasios
