### ISSUE TITLE
the variable loss_tables is not defined in graphical_bonferroni_search_HB

### ISSUE THREAD

**Issue by rguo12** [aangelopoulos/ltt#4]
you can find it here
https://github.com/aangelopoulos/ltt/blob/c30016b1e72432414d6f6067e7bfdfe73c8a2d6f/core/concentration.py#LL180C1-L181C1

**Comment by aangelopoulos** [comment]
Thank you, I think it was just a typo, and it should be `loss_table`.

**Comment by rguo12** [comment]
Great! That should work :)

**Comment by aangelopoulos** [comment]
Perfect, thanks for finding the bug :)
